FROM golang:1.21.1-alpine

WORKDIR /usr/src/storage

COPY ./services/go.mod ./services/go.sum ./

RUN go mod download && go mod verify

COPY ./services ./

RUN go build -v -o ./ ./cmd/storage/main.go

CMD [ "./main" ]