# The serverside type of your resource (the correct module for that type has to be loaded)
type = "js"
# The clientside type of your resource (the correct module for that type has to be loaded)
client-type = "js"
# The main serverside file that will get loaded when the server starts
main = "server/startup.js"
# The main clientside file that will get loaded when the client starts
client-main = "client/startup.js"
# The files that the client has access to (The client-main file does not have to be included here)
client-files = [
    "client/*",
    "shared/*"
]
# The required permissions to play on the server (these have to be accepted, otherwise the player can't join)
required-permissions = [
    "Screen Capture"
]
# The optional permissions to play on the server (these permissions can be declined by the user)
optional-permissions = [
    "WebRTC"
]
# The dependencies of this resource (All dependencies get loaded before the resource)
deps = [
    ""
]