FROM golang:1.21.1-alpine
WORKDIR /usr/src/user

COPY ./services/go.mod ./services/go.sum ./

RUN go mod download && go mod verify

COPY ./services ./
RUN go build -v -o ./ ./cmd/user/main.go

CMD [ "./main" ]